spring.datasource.url=jdbc:mysql://db-mysql:3306/demo_db?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# ===== SERVER =====
server.port=80
server.address=0.0.0.0

# ===== DATABASE SAFE MODE =====
spring.datasource.hikari.initialization-fail-timeout=0
spring.sql.init.continue-on-error=true
spring.jpa.defer-datasource-initialization=true

# KHÔNG fail nếu DB chưa có
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfigurationdocker compose up
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration